name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Nvim install config files
        run: |
          make nvim-install

      - name: Dotfiles install
        run: |
          make dotfiles-install

      - name: Apt install
        run: |
          make ubuntu-prepare -- --dry-run
